// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsa3zQUnOPhpn5d7rfXNUq9VjFLB0Ngbg',
    appId: '1:261094833059:web:2fffd38afe912c45eb3816',
    messagingSenderId: '261094833059',
    projectId: 'commune-app-29939',
    authDomain: 'commune-app-29939.firebaseapp.com',
    storageBucket: 'commune-app-29939.appspot.com',
    measurementId: 'G-2BCMSZ2VY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAchkGWk5mgm-7Pb9lsBOkHxx91eme5dUs',
    appId: '1:261094833059:android:d35fee390b8c64e7eb3816',
    messagingSenderId: '261094833059',
    projectId: 'commune-app-29939',
    storageBucket: 'commune-app-29939.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAykFC8fJB5I5pnVqNktsMdQ5FoU7__qsw',
    appId: '1:261094833059:ios:88493c225656ca74eb3816',
    messagingSenderId: '261094833059',
    projectId: 'commune-app-29939',
    storageBucket: 'commune-app-29939.appspot.com',
    iosBundleId: 'com.user.commune',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAykFC8fJB5I5pnVqNktsMdQ5FoU7__qsw',
    appId: '1:261094833059:ios:88493c225656ca74eb3816',
    messagingSenderId: '261094833059',
    projectId: 'commune-app-29939',
    storageBucket: 'commune-app-29939.appspot.com',
    iosBundleId: 'com.user.commune',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsa3zQUnOPhpn5d7rfXNUq9VjFLB0Ngbg',
    appId: '1:261094833059:web:c06c13b394a6ce90eb3816',
    messagingSenderId: '261094833059',
    projectId: 'commune-app-29939',
    authDomain: 'commune-app-29939.firebaseapp.com',
    storageBucket: 'commune-app-29939.appspot.com',
    measurementId: 'G-7GHB4GGYRN',
  );
}
